Vincentporte/add user model
betagouv/itou-communaute-django pull request #10
Opened 2022-09-15 12:56 UTC by vincentporte

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

2022-09-19 14:36 UTC, celine-m-s requested changes
Attention, il manque [des éléments](https://docs.djangoproject.com/fr/4.1/ref/applications/#configuring-applications) pour que l'app soit reconnue (et [la variable AUTH_USER_MODEL](https://docs.djangoproject.com/fr/4.1/topics/auth/customizing/#substituting-a-custom-user-model)). J'ai d'ailleurs du mal à comprendre comment ça peut fonctionner chez toi. Tu vois bien le modèle User dans l'admin Django ?

2022-09-19 14:36 UTC, celine-m-s commented on lacommunaute/users/apps.py
> +    default_auto_field = "django.db.models.BigAutoField"
Pourquoi cette valeur par défaut ?

2022-09-19 16:27 UTC, vincentporte commented on lacommunaute/users/apps.py
> +    default_auto_field = "django.db.models.BigAutoField"
Bien vu pour l'installed_app et le `AUTH_USER_MODEL` manquant.

2022-09-19 17:02 UTC, vincentporte commented on lacommunaute/users/apps.py
> +    default_auto_field = "django.db.models.BigAutoField"
J'aligne sur le fonctionnement de `itou`, pas de fichier `apps.py` + déclaration dans `LOCAL_APPS`

2022-09-19 17:03 UTC, vincentporte commented on lacommunaute/users/apps.py
> +    default_auto_field = "django.db.models.BigAutoField"
Le `BigAutoField` est une reco Django pour les clés primaires.

2022-09-20 08:02 UTC, celine-m-s commented on lacommunaute/users/apps.py
> +    default_auto_field = "django.db.models.BigAutoField"
Je suppose que tu fais référence [à cette doc](https://docs.djangoproject.com/fr/4.1/topics/db/models/#automatic-primary-key-fields) ? Ce n'est pas ce que j'en comprends. Le comportement normal de Django est de [créer l'ID automatiquement s'il n'est pas défini par le développeur](https://docs.djangoproject.com/fr/4.1/topics/db/models/#automatic-primary-key-fields) :

> Par défaut, Django donne à chaque modèle une clé primaire autoincrémentée dont le type est défini par application selon [AppConfig.default_auto_field](https://docs.djangoproject.com/fr/4.1/ref/applications/#django.apps.AppConfig.default_auto_field) ou globalement dans le réglage [DEFAULT_AUTO_FIELD](https://docs.djangoproject.com/fr/4.1/ref/settings/#std-setting-DEFAULT_AUTO_FIELD)

La valeur par défaut de `DEFAULT_AUTO_FIELD` étant `[django.db.models.AutoField](https://docs.djangoproject.com/fr/4.1/ref/models/fields/#django.db.models.AutoField)`, je ne vois pas de raison de la changer  dans le cas du modèle User.

BigAutoField est intéressant si on a besoin de conserver des entiers jusqu'à 9223372036854775807 (et non 2147483647 pour les IntegerFields). Mais ça fait quand même beaucoup d'utilisateurs, non ?

Chaque modification du comportement par défaut de Django entraîne de la maintenance et de la complexité, c'est pourquoi je préfère généralement m'en tenir aux recommandations du framework utilisé. De plus, chaque réglage par défaut ayant fait l'objet d'un débat entre développeurs, ils représentent des bonnes pratiques qui font consensus.

2022-10-04 12:22 UTC, merged