Ajout de Mailhog dans l'environnement de dev local
betagouv/itou-communaute-django pull request #12
Opened 2022-09-19 10:19 UTC by vincentporte

## Quoi ?

Ajout de Mailhog dans l'environnement de dev local

Remarque : PR checked-out à partir de la branche `vincentporte/add_user_model`.

## Pourquoi ?

    Disposer d'une UI de consultation des emails en local

Remarque : y a t il une opportunité à intégrer mailhog dans les recettes jetables pour la validation des emails métier.

## Comment ?

    - ajout de l'image docker
    - mise à jour des settings de dev

2022-09-19 14:17 UTC, celine-m-s requested changes
Mailhog est un service externe exposé dans un conteneur différent de celui de Django. Les variables définies dans config/settings/dev.py ne seront donc pas prises en compte car ce fichier n'est valable que pour Django. Je pense donc qu'il est possible de supprimer toutes les variables ajoutées dans `dev.py`.

2022-09-19 14:19 UTC, celine-m-s commented
> y a t il une opportunité à intégrer mailhog dans les recettes jetables pour la validation des emails métier.

Les recettes jetables utilisent les réglages de production. Dans le cas des e-mails, ils sont envoyés avec Mailjet. Il n'y a donc pas besoin d'un autre serveur d'e-mail puisque Mailjet joue ce rôle-là.

2022-09-19 17:27 UTC, vincentporte commented
> Mailhog est un service externe exposé dans un conteneur différent de celui de Django. Les variables définies dans config/settings/dev.py ne seront donc pas prises en compte car ce fichier n'est valable que pour Django. Je pense donc qu'il est possible de supprimer toutes les variables ajoutées dans `dev.py`.

Ces variables sont celles necessaires pour que Django envoie les emails vers mailhog. Tu as :100: raison, elles ne sont visibles que par Django. Ce sera dommage de les retirer, même si on envoie pas encore de mail.

2022-09-20 07:24 UTC, celine-m-s commented
Comme tu sens.

2022-09-20 07:28 UTC, celine-m-s commented on config/settings/dev.py
> +EMAIL_USE_TLS = False
Certaines variables sont configurées avec leurs valeurs par défaut. Je trouve ça perturbant de surcharger une variable par sa valeur par défaut mais bon, si vous voulez les garder comme ça, pourquoi pas.

2022-09-20 07:28 UTC, celine-m-s approved these changes
Dernier commit ok pour moi.

2022-09-20 08:13 UTC, celine-m-s commented
Essai pour Slack

2022-10-04 13:48 UTC, merged