Signup, Login et reinit du mot de passe
betagouv/itou-communaute-django pull request #20
Opened 2022-10-17 10:15 UTC by vincentporte

# Quoi ?

Creation d'un compte utilisateur avec l'email comme identifiant, connexion à son compte utilisateur et reinitialisation du mot de passe

# Comment ?

### modification du modèle`User` : 
- email unique, 
- username est un uuid aléatoire, laissé modifiable pour ne pas à avoir à surcharger l'admin à court terme
- pas de verification de l'email lors du signup, pourra être ajouté plus tard

### vues d'authentification : 
- réutilisation au maximum des vues existantes (`django.contrib.auth.urls.views`)
- création de la vue `SignupView`

### templates : 
- ajout de 2 mixins `auth_form.html` et `form_input.html` pour uniformiser les formulaires d'authentification

2022-10-17 10:25 UTC, vincentporte commented on requirements/base.txt
> +faker==15.1.1 ; python_version >= "3.10" and python_version < "4.0"
post it : deplacer `factory-boy` et `faker` dans les lib de dev dans une prochaine PR

2022-10-17 10:27 UTC, vincentporte commented on lacommunaute/www/users/tests/tests_forms.py
> +        self.assertIn("That email is already taken", form.errors["email"])
post it : à traduire :fr:

2022-10-17 12:36 UTC, hellodeloo approved these changes

2022-10-18 07:28 UTC, SebastienReuiller requested changes
Essentiellement des traductions 🇫🇷 😉

2022-10-18 07:28 UTC, SebastienReuiller commented on lacommunaute/templates/registration/login.html
> +                            {% include 'mixins/auth/auth_form.html' with form=form cta="Login" %}
Suggestion : en français, j'aurais dit "Se connecter" à la place de "Login"

2022-10-18 07:28 UTC, SebastienReuiller commented on lacommunaute/templates/registration/login.html
> +                            <a class="float-right" href="#" >Sign up</a>
Suggestion: en français 😉 "S'inscrire" et tu peux mettre le lien vers l'inscription que tu as faite, non ?

2022-10-18 07:28 UTC, SebastienReuiller commented on lacommunaute/templates/registration/password_reset.html
> +                    {% include 'mixins/auth/auth_form.html' with form=form cta="Reset Password" %}
Le terme passé par le paramètre `cta`, n'est pas traduit.

2022-10-18 07:28 UTC, SebastienReuiller commented on lacommunaute/templates/registration/password_reset_complete.html
> +                    <p><a class="btn btn-large btn-primary"  href="{% url 'users:login' %}" >Login</a></p>
"Se connecter" ?

2022-10-18 11:18 UTC, vincentporte commented
ok pour rester simple et supprimer le loader i18n. 
le bemol, ca nous oblige à surcharger TOUS les templates `machina` et ce n'est pas trop le plan à court terme.

@hellodeloo, si tu as l'outil magic pour gérer les locales 🛹 GO! inon, j'allais me coltiner les locales.

Je me note d'ajouter la balise `trans% sur tous les champs de cette PR.

qu'en pensez-vous ?

cc @SebastienReuiller

2022-10-19 08:37 UTC, SebastienReuiller commented
Je pense que le projet n'a pas vocation à s’internationaliser alors je mettrai du français dans les templates comme les autres projets.

2022-10-19 08:47 UTC, vincentporte commented
mise en stand by au profit d'inclusion connect

2022-10-25 10:01 UTC, vincentporte commented
Remplacé par Inclusion Connect 🎸

2022-10-25 10:01 UTC, closed without merging