Ajout du support et de la compression scss
betagouv/itou-communaute-django pull request #23
Opened 2022-10-17 15:25 UTC by hellodeloo

### Quoi ?

Ajout du support et de la compression scss.

### Pourquoi ?

Pour pouvoir ajouter des styles custom au projet et surcharger, si necessaire, le thème.

### Comment ?

Avec les dépendances django_compressor et django_libsass.

2022-10-18 07:19 UTC, SebastienReuiller requested changes

2022-10-18 07:19 UTC, SebastienReuiller commented on requirements/dev.txt
> +django-compressor==4.1 ; python_version >= "3.10" and python_version < "4.0"
@hellodeloo , je ne connais pas bien `django-compressor`, mais j'ai l'impression que tu en as besoin essentiellement en production. La compression doit se faire qu'en prod ? Si c'est bien le cas, il faut que la dépendance descende dans le `base.txt` et non dans le `dev.txt`.

2022-10-18 15:55 UTC, hellodeloo commented on requirements/dev.txt
> +django-compressor==4.1 ; python_version >= "3.10" and python_version < "4.0"
En prod, il n'y a plus de compression, le scss est devenu du css normalement, avec la compression avant commit dans le ficher `clevercloud/python.json`. Par contre en dev, la compression doit être live à chaque save. Donc je crois que ça doit rester dans dev.txt mais je suis pas certain de comprendre ce que je fais alors si tu préfères faire autrement, fait ça comme tu veux.

2022-10-24 11:49 UTC, SebastienReuiller commented on requirements/dev.txt
> +django-compressor==4.1 ; python_version >= "3.10" and python_version < "4.0"
@hellodeloo Ok, je te confirmes que dans ce cas tu as besoin de `django-compressor` dans les dépendances de prod aussi, car sans cette dépendance, la commande `compressor` du `clevercloud/python.json` ne pourra pas s'exécuter. On est d'accord que tu n'as pas besoin de versionner le fichier css généré, mais juste le `.scss` ?.

2022-10-25 09:19 UTC, closed without merging