Partager les sujets des forums sur les reseaux sociaux et par email
betagouv/itou-communaute-django pull request #52
Opened 2022-10-31 15:57 UTC by vincentporte

### Quoi ?

Partager les articles sur les réseaux sociaux et par email

### Pourquoi ?

Aider à l'onboarding des communautés existantes

### Comment ?

🍜 Ajout des lib [django-social-share](https://github.com/fcurella/django-social-share), et de la lib d'icones `fontawesomefree`
🍜 Adaptation des templatetags de `django-social-share` et intégration par un include.

### Autre (optionnel)

🦺 Pour tester cette PR, le site doit être accessible depuis www. Utiliser le tunnel `ngrok` et ajouter l'url fournie dans les `ALLOWED_HOSTS` de `dev.py`
🦺 Revoir l'intégration graphique
🦺 Revoir les textes d'accompagnement (email, whatspp, tweet)

2022-10-31 18:24 UTC, hellodeloo commented
@vincentporte Pour infos la lib d'icone "'Font Awesome 5 Free'" est déjà presente dans machina. Donc a priori, pas besoin de l'importer une 2eme fois

2022-11-02 05:07 UTC, vincentporte commented
Bien vu @hellodeloo, merci :star2:

2022-11-02 06:29 UTC, hellodeloo approved these changes

2022-11-03 17:15 UTC, vincentporte commented
je ne suis pas satisfait du rendu avec le plugin lk (awfull), mais ça fonctionne avec lk maintenant. 
@SebastienReuiller peux tu revoir stp ?

2022-11-07 10:22 UTC, SebastienReuiller requested changes

2022-11-07 10:22 UTC, SebastienReuiller commented on lacommunaute/templates/django_social_share/templatetags/post_to_linkedin.html
> +<script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: {{ LANGUAGE_CODE|linkedin_locale }}</script>
En effet, le rendu n'est pas top : 
![image](https://user-images.githubusercontent.com/17601807/200286613-b98b2079-7f50-4bc0-99d1-6f86524ff421.png)

Est-ce que tu ne peux pas revenir à ta version et juste encoder l'URL et virer les guillemets? À mon avis, ça passerait.

2022-11-07 10:39 UTC, hellodeloo commented
@vincentporte Quand j'aurai des fixtures en local, je repasserai sur ça pour mettre du propre et puis je remplacerai toutes les icônes "awesome icons" par les "remix icons" du thème

2022-11-07 15:16 UTC, vincentporte commented on lacommunaute/templates/django_social_share/templatetags/post_to_linkedin.html
> +<script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: {{ LANGUAGE_CODE|linkedin_locale }}</script>
hop, mis à jour et testé.

2022-11-08 10:38 UTC, SebastienReuiller approved these changes

2022-11-08 11:11 UTC, merged