Invitation des membres d'une communauté - Bonus - afficher le lien d'invitation pour les animateurs de la communauté
betagouv/itou-communaute-django pull request #58
Opened 2022-11-07 13:55 UTC by vincentporte

### Quoi ?

cf titre

### Pourquoi ?

pour faciliter l'obtention de l'URL sans passer par l'équipe de dev ni l'interface d'admin

### Comment ?

Vérifier les droits `can_approve_posts` de l'utilisateur et afficher l'URL en bas de page

2022-11-07 15:49 UTC, SebastienReuiller requested changes
Petit souci dans la structure HTML.

2022-11-07 15:49 UTC, SebastienReuiller commented on lacommunaute/templates/forum/forum_detail.html
> +    </div>
Ta fermeture de `div` est en dehors du block if 😬

2022-11-07 15:49 UTC, SebastienReuiller commented on lacommunaute/www/forum_member/tests.py
> +    # TODO vincentporte : fix this test with sebastien's help :D
Il doit passer ce test maintenant, si tu rebase, non ?

2022-11-07 16:11 UTC, vincentporte commented on lacommunaute/templates/forum/forum_detail.html
> +    </div>
:roll_eyes:  exact

2022-11-08 10:35 UTC, SebastienReuiller approved these changes
👍️

2022-11-08 10:49 UTC, merged