Recette Jetable
betagouv/itou-communaute-django pull request #81
Opened 2022-11-17 16:44 UTC by vincentporte

### Quoi ?

Environnement de validation

### Comment ?

Ajout des fichiers github actions de création et de suppression des review_app
Ajout du label `recette_jetable`

2022-11-17 16:45 UTC, vincentporte commented
note : les actions sont déclenchées mais skipped …

2022-11-22 15:22 UTC, SebastienReuiller requested changes
Une petite correction sur une variable d'env et un ajout pour que IC fonctionne en recette 🙏

2022-11-22 15:22 UTC, SebastienReuiller commented on .github/workflows/review-app-creation.yml
> +        $CLEVER_CLI env set ITOU_ENVIRONMENT "REVIEW-APP"
Nous l'avions renommée en "COMMU_ENVIRONMENT". Tu peux donc remplacer le ITOU_ENVIRONMENT.
J'ai fait la configuration d'IC et j'aurais besoin que tu set ici la variable d'environnement : "COMMU_FQDN".
Quelque chose du genre : `$CLEVER_CLI env set COMMU_FQDN "${{ env.DEPLOY_URL }}"`

2022-11-23 10:41 UTC, SebastienReuiller approved these changes
Top ! 🚀

2022-11-23 10:42 UTC, merged